package com.io7m.jsom0.parser;

public enum ModelObjectTokenType
{
  OBJECT_TOKEN_EOF,
  OBJECT_TOKEN_LITERAL_DECIMAL,
  OBJECT_TOKEN_LITERAL_FLOAT,
  OBJECT_TOKEN_SEMICOLON,
  OBJECT_TOKEN_SYMBOL,
  OBJECT_TOKEN_LITERAL_STRING,
}
